# Generated by Django 5.0 on 2023-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('product_mfg', models.DateTimeField()),
                ('product_sku', models.IntegerField()),
            ],
        ),
    ]
